// API 1
GET http://localhost:3006/states/
###

// API 2
GET http://localhost:3006/states/2/
###

// API 3
POST http://localhost:3006/districts/
Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}
###

// API 4
GET http://localhost:3006/districts/764/
###

// API 5
DELETE http://localhost:3006/districts/765/
###

// API 6
PUT http://localhost:3006/districts/764/
Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}
###

// API 7
GET http://localhost:3006/states/3/stats/
###

// API 8
GET http://localhost:3006/districts/9/details/
###
